# Generated by Django 4.0.5 on 2022-07-18 09:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Service', models.CharField(max_length=200)),
                ('Preacher', models.CharField(max_length=200)),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Poster', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('Sermon', models.TextField()),
            ],
        ),
    ]
