# Generated by Django 4.0.5 on 2022-07-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermons',
            name='Service',
            field=models.CharField(choices=[('TS', 'Tuesday Service'), ('SS', 'Sunday Service')], max_length=200),
        ),
    ]
