# Generated by Django 4.0.5 on 2022-07-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sermons_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermons',
            name='Poster',
            field=models.ImageField(blank='True', upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='sermons',
            name='Service',
            field=models.CharField(choices=[('Tuesday Service', 'Tuesday Service'), ('Sunday Service', 'Sunday Service')], max_length=200),
        ),
    ]
