# Generated by Django 4.0.5 on 2022-07-18 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_sermons_poster_alter_sermons_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sermons',
            new_name='Sermon',
        ),
    ]
