# Generated by Django 4.0.5 on 2022-07-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_sermons_sermon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sermon',
            name='Scriptures',
            field=models.CharField(default='', max_length=200),
        ),
    ]
