# Generated by Django 4.0.5 on 2022-07-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_sermon_scriptures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='Scriptures',
        ),
        migrations.AddField(
            model_name='sermon',
            name='Scripture',
            field=models.CharField(default=1, max_length=200),
        ),
    ]
