# Generated by Django 4.0.5 on 2022-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_sermon_scriptures_sermon_scripture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='Scripture',
            field=models.CharField(default=1, max_length=2000),
        ),
    ]
