# Generated by Django 4.0.5 on 2022-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_sermon_scripture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='Scripture',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
