# Generated by Django 4.0.5 on 2022-07-26 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_sermon_scripture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Poster', models.ImageField(blank='True', upload_to='photos/%Y/%m/%d')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Head', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank='True', upload_to='photos/%Y/%m/%d')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Head', models.CharField(max_length=200)),
                ('Photo', models.ImageField(blank='True', upload_to='photos/%Y/%m/%d')),
                ('Description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sermon',
            name='Sermon_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
