# Generated by Django 4.0.5 on 2022-07-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_activity_family_team_sermon_sermon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='Venue',
            field=models.CharField(default='', max_length=200),
        ),
    ]
