# Generated by Django 4.0.5 on 2022-09-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_activity_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Poster',
            field=models.ImageField(blank='True', upload_to=''),
        ),
    ]
