# Generated by Django 4.0.5 on 2022-10-03 07:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_week_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_message',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 7, 21, 7, 399972, tzinfo=utc)),
        ),
    ]
