# Generated by Django 4.0.5 on 2022-10-03 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_week_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_message',
            name='Date',
            field=models.DateField(default=datetime.datetime(2022, 10, 3, 7, 22, 4, 455186, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='week_message',
            name='Name',
            field=models.CharField(choices=[('Reverend', 'Reverend'), ('Youth Patron', 'Youth Patron'), ('Youth Coordinator', 'Youth Coordinator')], max_length=200),
        ),
    ]
