# Generated by Django 4.0.5 on 2022-10-03 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_week_message_date_alter_week_message_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_message',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
