# Generated by Django 4.0.5 on 2022-11-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('District', models.CharField(max_length=200)),
                ('Person', models.CharField(max_length=200)),
                ('Date', models.DateField()),
            ],
        ),
    ]
