# Generated by Django 4.0.5 on 2022-11-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Number', models.IntegerField()),
                ('Area', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Confirmed', models.BooleanField()),
            ],
        ),
    ]
