# Generated by Django 4.0.5 on 2022-11-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_membership_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='Confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
