# Generated by Django 4.0.5 on 2022-11-16 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_membership_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Phone_number', models.IntegerField()),
                ('District', models.CharField(max_length=200)),
                ('Activity', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.activity')),
            ],
        ),
    ]
