# Generated by Django 4.0.5 on 2022-11-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Amount',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='Paid',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
