# Generated by Django 4.0.5 on 2022-11-16 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_booking_amount_alter_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Amount',
            field=models.IntegerField(default=''),
        ),
    ]
