# Generated by Django 4.0.5 on 2022-11-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_booking_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join_Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Team', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.team')),
            ],
        ),
        migrations.CreateModel(
            name='Join_Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Number', models.CharField(max_length=200)),
                ('District', models.CharField(max_length=200)),
                ('Family', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.family')),
            ],
        ),
    ]
