# Generated by Django 4.0.5 on 2023-01-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_join_family_family'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Number',
            field=models.CharField(max_length=200),
        ),
    ]
