# Generated by Django 4.0.5 on 2023-01-09 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_payment_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='Paid_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
