# Generated by Django 4.1.5 on 2023-01-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_payment_name_payment_paid_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='Poster',
            field=models.ImageField(blank='True', upload_to='new'),
        ),
    ]
