# Generated by Django 4.1.5 on 2023-01-16 11:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_sermon_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Detail', models.TextField()),
                ('Poster', models.ImageField(upload_to='new')),
                ('Date_posted', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='family',
            old_name='Head',
            new_name='Leader',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='Head',
            new_name='Leader',
        ),
        migrations.AlterField(
            model_name='activity',
            name='Poster',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.activity'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='Photo',
            field=models.ImageField(upload_to='new'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='Confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='Poster',
            field=models.ImageField(upload_to='new'),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='Scripture',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='Sermon_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='Photo',
            field=models.ImageField(upload_to='new'),
        ),
    ]
