# Generated by Django 4.1.5 on 2023-01-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_announcement_rename_head_family_leader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermon',
            name='Poster',
            field=models.ImageField(blank=True, upload_to='new'),
        ),
    ]
