# Generated by Django 4.1.5 on 2023-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_sermon_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='week_message',
            name='Photo',
            field=models.ImageField(default=0, upload_to='new'),
            preserve_default=False,
        ),
    ]
